ERROR    root:tasks.py:54 Reencryption d6df93ac-8db1-4ef6-af5c-8952083a8454: Wrong applet 5602ff15-fb42-4c7f-97d9-37c6984487a5 encryption format, skip
ERROR    root:tasks.py:55 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 52, in reencrypt_answers
    applet_pub_key = json.loads(applet.encryption.public_key)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)