WARNING  api.access:structured_logs.py:183 {'http': {'url': 'http://test.com/users/me/events/c65eadb1-d4b8-49e7-81dc-9f236198c9d3', 'request_path': '/users/me/events/c65eadb1-d4b8-49e7-81dc-9f236198c9d3', 'status_code': 403, 'method': 'GET', 'request_id': '4fa6cc82d22e4e8092696c126b6026c1', 'version': '1.1'}, 'network': {'client': {'ip': '127.0.0.1', 'port': 123}}, 'duration': 12201881, 'event': '127.0.0.1:123 - "GET http://test.com/users/me/events/c65eadb1-d4b8-49e7-81dc-9f236198c9d3 HTTP/1.1" 403', 'request_id': '4fa6cc82d22e4e8092696c126b6026c1', 'logger': 'api.access', 'level': 'warning', 'timestamp': '2025-03-31T13:23:55.416347Z'}